### ISSUE TITLE
13-04-2020 Team 104 The Fornax

### ISSUE THREAD

**Issue by OdongAlican** [rajkumardas2701/Bootstrap-Newsweek#2]
Great Job. Keep up the good work.
Just a few recommendations;
- Please try to use some bootstrap classes for padding, margins, and positions.
- Use the class "row " to the parent divs.
- Please use only one CSS file. 
Once again Great Job!

**Comment by rajkumardas2701** [comment]
Thank you, suggestions added to the project.
