### ISSUE TITLE
17-04-2020 Team-104-the-Fornax

### ISSUE THREAD

**Issue by MrSayyod** [rajkumardas2701/Bootstrap-Newsweek#3]
1. Please, work with the padding on your "Editor's pick" part.
2. From the navbar delete the place name on the small screen size.
3. From the footer delete the borders on the small screen size.
Great work! Keep it up!

**Comment by rajkumardas2701** [comment]
Thank you Team 104 the Fornax, changes has been implemented. :)

Regards,
Rajkumar Das
